labels:
  - name: "🐞 bug"
    color: "d73a4a"
    description: "버그 수정이 필요한 이슈"

  - name: "🚀 feature"
    color: "0e8a16"
    description: "새로운 기능 추가"

  - name: "⚙️ chore"
    color: "c5def5"
    description: "유지보수 및 설정 관련 작업"

  - name: "⚡ hotfix"
    color: "ff4500"
    description: "긴급한 버그 또는 문제 해결"

  - name: "🔨 refactor"
    color: "ffcc00"
    description: "기능 변경 없이 코드 개선"

  - name: "🧪 test"
    color: "9966ff"
    description: "테스트 코드 작성 및 리팩토링"

  - name: "📖 docs"
    color: "0075ca"
    description: "문서 추가 및 업데이트"
