name: "🐞 Bug Report"
description: "버그를 발견했다면 이 템플릿을 사용해주세요."
title: "[🐞 Bug]: "
labels: ["🐞 bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 버그 리포트  
        버그에 대한 자세한 내용을 작성해주세요.

  - type: textarea
    id: bug-description
    attributes:
      label: "📄 버그 설명"
      description: "어떤 문제가 발생했나요?"
      placeholder: "버그가 발생한 상황을 상세히 적어주세요."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "🔄 재현 방법"
      description: "버그를 재현할 수 있는 방법을 단계별로 작성해주세요."
      placeholder: "1. 특정 페이지로 이동 → 2. 버튼 클릭 → 3. 오류 발생"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "✅ 기대하는 동작"
      description: "원래 어떻게 동작해야 하나요?"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: "🖥 환경 정보"
      multiple: true
      options:
        - "Windows"
        - "MacOS"
        - "Linux"
        - "iOS"
        - "Android"
    validations:
      required: true
