name: "⚙️ Chore"
description: "유지보수 작업을 진행하려면 이 템플릿을 사용하세요."
title: "[⚙️ Chore]: "
labels: ["⚙️ chore"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚙️ 유지보수 작업  
        변경 사항을 설명해주세요.

  - type: textarea
    id: chore-description
    attributes:
      label: "📄 작업 내용"
      description: "어떤 유지보수 작업을 수행할 예정인가요?"
    validations:
      required: true

  - type: checkboxes
    id: chore-tasks
    attributes:
      label: "📝 체크리스트"
      options:
        - label: "환경 변수 업데이트"
        - label: "패키지 버전 업데이트"
        - label: "빌드 스크립트 수정"
