name: ⚙️ Chore
description: 빌드, 패키지, 설정 파일, 환경 변수 등 기능/버그 수정 외의 작업을 수행합니다.
title: "[⚙️ Chore] "
labels: ["⚙️ chore"]
body:
  - type: textarea
    id: chore-description
    attributes:
      label: 📄 설명
      description: |
        작업에 대한 설명을 자세히 작성해 주세요.
        -
      placeholder: |
        예:
        - Webpack 설정 최적화
        - CI/CD 파이프라인 수정
        - npm 패키지 업데이트
        - 환경 변수 추가 및 수정
    validations:
      required: true

  - type: textarea
    id: chore-tasks
    attributes:
      label: ⚙️ 작업 목록
      description: |
        수행해야 할 작업을 체크박스로 작성해 주세요.
        -
      placeholder: |
        예:
        - [ ] `.env` 파일에 새로운 환경 변수 추가
        - [ ] `package.json`에서 `react` 패키지 버전 업데이트
        - [ ] ESLint 설정 수정
    validations:
      required: true

  - type: textarea
    id: chore-more
    attributes:
      label: 📝 추가 정보
      description: 더 하고 싶은 말이 있다면 작성해 주세요.
      placeholder: "예: 변경 사항이 프로젝트에 미치는 영향, 관련 문서 링크 등"
    validations:
      required: false
