name: 📖 Documentation
description: 문서를 추가하거나 수정하는 이슈입니다.
title: '[📖 Docs] '
labels: ['📖 docs']
body:
  - type: markdown
    attributes:
      value: |
        ## 📄 설명  
        문서 수정 또는 추가할 내용을 작성해 주세요.

  - type: textarea
    id: documentation-description
    attributes:
      label: "문서 설명"
      placeholder: |
        예:
        - README.md에 프로젝트 소개 추가
        - API 문서 업데이트
        - 새로운 개발 가이드 문서 작성
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## ✍️ 변경 이유  
        이 문서 변경이 필요한 이유를 설명해 주세요.

  - type: textarea
    id: documentation-reason
    attributes:
      label: "변경 이유"
      placeholder: |
        예:
        - 기존 문서가 최신 상태가 아님
        - 신규 기능에 대한 문서가 필요함
        - 문서 내용이 부족하여 보완 필요
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📂 관련 문서  
        이 문서와 관련된 다른 문서가 있다면 링크를 추가해 주세요.

  - type: textarea
    id: related-docs
    attributes:
      label: "관련 문서"
      placeholder: "예: [API 문서](https://example.com/api-docs)"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 📝 추가 정보  
        추가로 공유하고 싶은 내용이 있다면 작성해 주세요.

  - type: textarea
    id: documentation-more
    attributes:
      label: "추가 정보"
      placeholder: "예: 
