name: 📖 Documentation
description: 문서를 추가하거나 수정하는 이슈입니다.
title: "[📖 Docs] "
labels: ["📖 docs"]
body:
  - type: textarea
    id: documentation-description
    attributes:
      label: 📄 설명
      description: |
        문서 수정 또는 추가할 내용을 작성해 주세요.
        -
      placeholder: |
        예:
        - README.md에 프로젝트 소개 추가
        - API 문서 업데이트
        - 새로운 개발 가이드 문서 작성
    validations:
      required: true

  - type: textarea
    id: documentation-reason
    attributes:
      label: ✍️ 변경 이유
      description: |
        이 문서 변경이 필요한 이유를 설명해 주세요.
        -
      placeholder: |
        예:
        - 기존 문서가 최신 상태가 아님
        - 신규 기능에 대한 문서가 필요함
        - 문서 내용이 부족하여 보완 필요
    validations:
      required: true

  - type: textarea
    id: documentation-more
    attributes:
      label: 📝 추가 정보
      description: 추가로 공유하고 싶은 내용이 있다면 작성해 주세요.
      placeholder: "예: 관련 문서 링크, 참고할 외부 자료 등"
    validations:
      required: false
