name: ⚡ Hotfix
description: 긴급한 버그 수정을 위한 이슈입니다.
title: "[⚡ Hotfix] "
labels: ["⚡ hotfix"]
body:
  - type: textarea
    id: hotfix-description
    attributes:
      label: 📄 설명
      description: |
        긴급한 버그에 대한 설명을 작성해 주세요.
        -
      placeholder: |
        예:
        - 결제 API가 응답하지 않음
        - 서버 다운으로 인해 모든 요청 실패
        - 로그인 불가 문제 발생
    validations:
      required: true

  - type: textarea
    id: hotfix-more
    attributes:
      label: 📝 추가 정보
      description: 추가로 공유하고 싶은 내용이 있다면 작성해 주세요.
      placeholder: "예: 해당 버그가 발생한 특정 시간대, 로그 정보 등"
    validations:
      required: false
