name: 🧪 test
description: 테스트 코드를 작성하거나 기존 테스트 코드를 리팩토링합니다.
title: "[🧪 test] "
labels: ["🧪 test"]
body:
  - type: markdown
    attributes:
      value: "테스트 대상에 대해서 기본적인 내용을 작성해주세요"
  - type: textarea
    id: test-description
    attributes:
      label: 🧪 테스트 요약
      description: |
        - 테스트 대상(기능/모듈/화면)과 목적(테스트가 필요한 이유, 테스트로 확인하고 싶은 내용)을 자세히 작성해 주세요.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: test-os
    attributes:
      label: 🧪 테스트 환경
      description: |
        테스트 테스트 환경(OS / 브라우저 / 버전 / 서버 백엔드 등)을 자세히 작성해 주세요.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: test-case
    attributes:
      label: 🧪 테스트 시나리오
      description: |
        - 테스트 테스트 환경(OS / 브라우저 / 버전 / 서버 백엔드 등)을 자세히 작성해 주세요.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: test-result
    attributes:
      label: 🧪 테스트 결과
      description: |
        예상 결과와 실제 테스트 결과를 작성해 주세요.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: test-more
    attributes:
      label: 📝 메모
      description: 더 하고 싶은 말이 있다면 작성해 주세요.
    validations:
      required: false
