name: 🎨 UI/UX 개선
description: UI/UX 디자인을 추가하거나 수정하는 이슈입니다.
title: "[🎨 UI/UX] "
labels: ["🎨 ui/ux"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📄 설명  
        개선할 UI/UX 요소에 대한 설명을 자세히 작성해 주세요.

  - type: textarea
    id: ui-description
    attributes:
      label: "UI/UX 설명"
      placeholder: |
        예:
        - 로그인 버튼 크기를 조정하여 접근성 개선
        - 다크 모드 디자인 추가
        - 폰트 크기 및 컬러 조정
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📝 추가 정보  
        추가로 공유하고 싶은 내용이 있다면 작성해 주세요.

  - type: textarea
    id: ui-more
    attributes:
      label: "추가 정보"
      placeholder: "예: 관련 디자인 레퍼런스 링크, Figma URL 등"
    validations:
      required: false
